# Generated by Django 5.2.3 on 2025-07-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(choices=[('technical', 'Technical Issues'), ('account', 'Account Issues'), ('billing', 'Billing and Payments'), ('product', 'Product/Service Support'), ('feedback', 'Feedback and Suggestions'), ('security', 'Security Concerns'), ('other', 'Other')], default='other', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(choices=[('tech_support', 'Technical Support'), ('customer_service', 'Customer Service'), ('billing', 'Billing & Accounts'), ('product_support', 'Product Support'), ('sales', 'Sales & Marketing'), ('security', 'Security & Compliance'), ('admin', 'Administration'), ('other', 'Other')], default='other', max_length=50, unique=True),
        ),
    ]
